### ISSUE TITLE
Couldn't Install Package because of Typescript Version

### ISSUE THREAD

**Issue by rjvim** [vitalics/ajv-ts#21]
**Describe the bug**
`npm install ajv-ts` didn't succeed.

```
npm install ajv-ts
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: hyperbola-investor@undefined
npm ERR! Found: typescript@5.3.3
npm ERR! node_modules/typescript
npm ERR!   dev typescript@"^5.1.6" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@"5.0.0" from ajv-ts@0.3.1
npm ERR! node_modules/ajv-ts
npm ERR!   ajv-ts@"*" from the root project
```

**To Reproduce**
1. Install latest Remix application
2. Run `npm install ajv-ts`
3. Notice above error

**Expected behavior**
Installation should work, shouldn't depend on a single version of Typescript?

**Desktop (please complete the following information):**
 - JS runtime : NodeJS

**Comment by vitalics** [comment]
As a workaround, I can recommend installing with `--force` flag until fixed.
