### ISSUE TITLE
Object required and optional properties misbehaving

### ISSUE THREAD

**Issue by nemostein-vlgl** [vitalics/ajv-ts#71]
**Describe the bug**
`s.object` properties are optional by default, but should be required

`.optional()` is an alias to `.nullable()`, but they aren't the same
A `nullable` property can be optional or required and a `optional` property can be non-`nullable`

**To Reproduce**
Objects being `.optional()` by default:
```js
const schema = s.object({ x: s.integer() })
const parsed = schema.parse({ y: true }) // Doesn't throw
console.log(parsed) // { y: true }
// Missing required: ['x']
console.log(schema._schema) // { type: 'object', properties: { x: { type: 'integer' } } }
```

Optional properties being `nullable`:
```js
const schema = s.object({ x: s.integer().optional() })
console.dir(schema._schema, { depth: null })
/*
{
  type: 'object',
  properties: {
    x: { anyOf: [ { type: 'integer' }, { type: 'null' } ] }
  }
}
*/
```

Together, they produce the following (incorrect) schema:
```js
const schemaWrong = s.object({
  x: s.integer(),
  y: s.integer().optional()
})
console.dir(schemaWrong._schema, { depth: null })

/*
{
  type: 'object',
  properties: {
    x: { type: 'integer' },
    y: { anyOf: [ { type: 'integer' }, { type: 'null' } ] }
  }
}
*/
```
This schema means that:
 - property `x` is an `optional` `integer`
 - property `y` is an `optional` `nullable` `integer`

**Expected behavior**

The correct behavior would be:
 - property `x` is a `required` `integer`
 - property `y` is an `optional` `integer`

A possible way to reproduce the expected behavior is to merge a `.required()` schema with a another that doesn't have `.optional()` properties, like this:
```js
const schemaReq = s.object({ x: s.integer() }).required()
const schemaOpt = s.object({ y: s.integer() })
const schemaExpected = schemaReq.merge(schemaOpt)

console.dir(schemaExpected._schema, { depth: null })

/*
{
  type: 'object',
  properties: { x: { type: 'integer' }, y: { type: 'integer' } },
  required: [ 'x' ]
}
*/
```

It's expected that `schemaWrong` and `schemaExpected` to be the same

**Comment by vitalics** [comment]
@nemostein-vlgl thanks for the issue. 
I check out your examples and compared with an [`ajv` package](https://ajv.js.org/) and here is a result.

1. [example](https://stackblitz.com/edit/stackblitz-starters-dhzw6c?file=index.js)
``` ts
const schema = s.object({ x: s.integer() })
const parsed = schema.parse({ y: true }) // Doesn't throw
console.log(parsed) // { y: true }
console.log(schema._schema)

// AJV usage
import Ajv from 'ajv'
const ajv = new Ajv()

const validateFn = ajv.compile({ type: 'object', properties: { x: { type: 'integer' } } }) // Schema from first example
const isValid = validateFn({ y: true }) 
console.log(isValid) // true
```

2. [example](https://stackblitz.com/edit/stackblitz-starters-9jdvmy?file=index.js)
``` ts
import s from 'ajv-ts';
import Ajv from 'ajv';

const schema = s.object({ x: s.integer().optional() });
console.dir(schema.schema, { depth: null });
/*
{
  type: 'object',
  properties: {
    x: { anyOf: [ { type: 'integer' }, { type: 'null' } ] }
  }
}
*/

const ajv = new Ajv();

const validateFn = ajv.compile({
  type: 'object',
  properties: {
    x: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
  },
});

const result = validateFn({ y: true });
console.log('result:', result); // true
```
I also checked the [json-schema spec](https://json-schema.org/understanding-json-schema/reference/object#properties) and there is no bug since you need to define required properties with the `required` keyword.

Example JSON-schema:
```json
{
  "type": "object",
  "properties": {
    "number": { "type": "number" },
    "street_name": { "type": "string" },
    "street_type": { "enum": ["Street", "Avenue", "Boulevard"] }
  }
}
```
OK schemas:
``` json
{ }
```
```json
{ "number": 1600, "street_name": "Pennsylvania" }
```

Given this context **expected behavior** is:

- property `x` is an `optional` and `integer`
- property `y` is an `optional` and (`integer` or `null`)

Feel free to add more examples that don't cover your expectations.

**Comment by nemostein-vlgl** [comment]
For the 1st example, I'd say that the behavior is unexpected based on 3 things.
- There is no `.required()` method for values (only for objects, marking every property as required)
- In Typescript, properties are required by default, which I think this lib should adheres to (the TS behavior)
- The examples in the README clearly states that object properties are required by default:
![image](https://github.com/user-attachments/assets/ea4ac423-28d4-459d-97f6-8e8d82063c1e)
As your example demonstrates, the schema fed to `ajv.compile()` lacks a `required: ['x']`

The 2nd example feels like a bug in TS, although its (arguably) correct for JSON Schema.
A optional property `x?: number` can only be a `number` or `undefined` (which is defined by its absence),  same for optional arguments
```ts
interface A {
  x?: number // number | undefined
}
const a: A = { x: null } // Type 'null' is not assignable to type 'number | undefined'.

function a (x?: number /* number | undefined*/) {}
b(null) // Argument of type 'null' is not assignable to parameter of type 'number | undefined'.
```

A value being `null` has a completely different semantics.
It means that the property/argument was set to something that means _no value_.

AJV or JSON Schema may not differentiate `undefined` from `null`, but Typescript certainly do!
